"""Builds SD2Cloud's credentials.h from the OAuth client JSON (Google Cloud > Clients > Download JSON).

usage: python tools/make_credentials.py <client_secret_....json> src/credentials.h

credentials.h stays out of git (.gitignore). For installed apps Google says the client secret "is not treated as a
secret" (it ends up inside the ELF anyway), but it doesn't need to live in the repository.
"""
import json
import sys

data = json.load(open(sys.argv[1], encoding="utf-8"))
client = data.get("installed") or data.get("web") or next(iter(data.values()))
cid, secret = client["client_id"], client["client_secret"]
for v in (cid, secret):
    if '"' in v or "\\" in v:
        sys.exit("unexpected value in the JSON")
with open(sys.argv[2], "w", encoding="ascii", newline="\n") as f:
    f.write("/* generated by tools/make_credentials.py -- NOT for git */\n")
    f.write(f'#define GOOGLE_CLIENT_ID "{cid}"\n')
    f.write(f'#define GOOGLE_CLIENT_SECRET "{secret}"\n')
print(f"credentials.h: client {cid.split('-')[0]}-...")
